sudo: false
dist: trusty


branches:
  only:
   - master
   - /^v\d+\.\d+\.\d+$/

language: java
jdk:
  - oraclejdk8
matrix:
  include:
    - language: python
      python: 3.6

# modify your email to recieve the result
notifications:
  email:
    - 358489360@qq.com

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - /bin/bash project/security_audit.sh
#  - /bin/bash project/build-ci.sh
#  - chmod +x ./gradlew
#  - ./gradlew build
#  - ./gradlew check
#  - ./gradlew codeCoverageReport
after_success:
  - bash <(curlrt.xml" -s https://codecov.io/bash) -f "./build/customJacocoReportDir/codeCoverageReport/codeCoverageRepo