# web container
server:
  port: 8080
  servlet:
    context-path: /

# log4j2
logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: weevent-gateway
  pid:
    fail-on-write-error: true
    file: ./logs/${spring.application.name}.pid
  jmx:
    enabled: false
  cloud:
    # discovery
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        instance-host: ${spring.cloud.client.ip-address}
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        root: WeEvent/services
      enabled: true
    # gateway
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
      httpclient:
        connect-timeout: 5000
        response-timeout: 10000
      routes:
        # sock js info
        - id: weevent-broker-sockjs-info
          uri: lb://weevent-broker
          predicates:
            - Path=/weevent-broker/sockjs/info/**
        # websocket of stomp & sock js & mqtt
        - id: weevent-broker-websocket
          uri: lb:ws://weevent-broker
          predicates:
            - Path=/weevent-broker/stomp/**
            - Path=/weevent-broker/sockjs/**
            - Path=/weevent-broker/mqtt/**
        # broker
        - id: weevent-broker
          uri: lb://weevent-broker
          predicates:
            - Path=/weevent-broker/**
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: "#{@UriKeyResolver}"
                local-memory-rate-limiter:
                  replenish-rate: 100
                  burst-capacity: 200
        # governance
        - id: weevent-governance
          uri: lb://weevent-governance
          predicates:
            - Path=/weevent-governance/**
        # processor
        - id: weevent-processor
          uri: lb://weevent-processor
          predicates:
            - Path=/weevent-processor/**